#!/bin/sh

. /lib/functions.sh

LOGGER_TAG="RESET BUTTON"
OVERLAY="$( grep ' /overlay ' /proc/mounts )"

case "$ACTION" in
pressed)
	[ -z "$OVERLAY" ] && return 0

	return 5
;;
timeout)
	. /etc/diag.sh
	set_state failsafe
;;
released)
	if [ "$SEEN" -lt 1 ]
	then
		echo "REBOOT" > /dev/console
		sync
		reboot
	elif [ "$SEEN" -ge 5 -a -n "$OVERLAY" ]
	then
		echo "FACTORY RESET" > /dev/console
		if [ "$(uci -q get ddmesh.system.ignore_factory_reset_button)" = "1" ]
			logger -t "$LOGGER_TAG" "factory reset button pressed -> disabled"
		else
			logger -t "$LOGGER_TAG" "factory reset button pressed"
			jffs2reset -y && reboot &
		fi
	fi
;;
esac

return 0
