stages:
- build

build:firmware:
  image: openwrt-docker-build:latest
  stage: build
  cache:
    key: ${CI_COMMIT_REF_SLUG}-master
    paths:
    - dl/*
  script:
    - bash build.sh openwrt:ar71xx.tiny 
  artifacts:
    paths:
    - workdir/*/bin/targets/*
  tags:
  - docker
