stages:
- init
- build
- test
- deploy

include:
  - local: '/gitlab-ci/m3runner-tags.yml'
  - local: '/gitlab-ci/m3runner-master.yml'
  - local: '/gitlab-ci/docker2-yaro.yml'
  - local: '/gitlab-ci/docker.yml'

