stages:
- build


####### docker ############
#build:ar71xx.tiny:
#  image: openwrt-docker-build:latest
#  stage: build
#  cache:
#    key: ${CI_COMMIT_REF_SLUG}-master
#    paths:
#    - dl/*
#  script:
#    - ./build.sh ar71xx.tiny
#  artifacts:
#    paths:
#    - workdir/*/bin/targets/*
#  tags:
#  - docker
#
#build:ar71xx.generic:
#  image: openwrt-docker-build:latest
#  stage: build
#  cache:
#    key: ${CI_COMMIT_REF_SLUG}-master
#    paths:
#    - dl/*
#  script:
#    - ./build.sh ar71xx.generic
#  artifacts:
#    paths:
#    - workdir/*/bin/targets/
#  tags:
#  - docker
#
#
#build:x86.generic:
#  image: openwrt-docker-build:latest
#  stage: build
#  cache:
#    key: ${CI_COMMIT_REF_SLUG}-master
#    paths:
#    - dl/*
#  script:
#    - ./build.sh x86.generic
#  artifacts:
#    paths:
#    - workdir/*/bin/targets/*
#  tags:
#  - docker
#
#build:ramips.mt7621.ubiquiti-edgerouter-x:
#  image: openwrt-docker-build:latest
#  stage: build
#  cache:
#    key: ${CI_COMMIT_REF_SLUG}-master
#    paths:
#    - dl/*
#  script:
#    - ./build.sh ramips.mt7621.ubiquiti-edgerouter-x
#  artifacts:
#    paths:
#    - workdir/*/bin/targets/*
#  tags:
#  - docker
#

######## m2runner ################
# there are two jobs, one for each commit and one for nightly scheduled job
# nightly is the one that keeps artifacts (result of built) and which
# then deployed later (see option "only").
# deploy stage should be added.
build:ar71xx.tiny:
  except:
    - schedules
  stage: build
  cache:
    untracked: true
    key: ${CI_COMMIT_REF_SLUG}
    paths:
    - dl
    - workdir/*
  script:
    - ./build.sh ar71xx.tiny -j2
  tags:
  - m2runner

nightly_build:ar71xx.tiny:
  only:
    - schedules
  stage: build
  cache:
    untracked: true
    key: ${CI_COMMIT_REF_SLUG}
    paths:
    - dl
# don't keep workdir
  script:
    - ./build.sh ar71xx.tiny -j8
#  artifacts:
#    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
#    paths:
#    - workdir/*/bin/targets/ar71xx/tiny
#    - dl
  tags:
  - m2runner

build:ar71xx.generic:
  except:
    - schedules
  stage: build
  cache:
    untracked: true
    key: ${CI_COMMIT_REF_SLUG}
    paths:
    - dl
    - workdir/*
  script:
    - ./build.sh ar71xx.generic -j2
  tags:
  - m2runner

nightly_build:ar71xx.generic:
  only:
    - schedules
  stage: build
  cache:
    untracked: true
    key: ${CI_COMMIT_REF_SLUG}
    paths:
    - dl
# don't keep workdir
  script:
    - ./build.sh ar71xx.generic -j8
#  artifacts:
#    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
#    paths:
#    - workdir/*/bin/targets/ar71xx/generic
#    - dl
  tags:
  - m2runner

build:x86.generic:
  except:
    - schedules
  stage: build
  cache:
    untracked: true
    key: ${CI_COMMIT_REF_SLUG}
    paths:
    - dl
    - workdir/*
  script:
    - ./build.sh x86.generic -j2
  tags:
  - m2runner

nightly_build:x86.generic:
  only:
    - schedules
  stage: build
  cache:
    untracked: true
    key: ${CI_COMMIT_REF_SLUG}
    paths:
    - dl
# don't keep workdir
  script:
    - ./build.sh x86.generic -j8
#  artifacts:
#    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
#    paths:
#    - workdir/*/bin/targets/x86/generic
#    - dl
  tags:
  - m2runner

build:ramips.mt7621:
  except:
    - schedules
  stage: build
  cache:
    untracked: true
    key: ${CI_COMMIT_REF_SLUG}
    paths:
    - dl
    - workdir/*
  script:
    - ./build.sh ramips.mt7621 -j2
  tags:
  - m2runner

nightly_build:ramips.mt7621:
  only:
    - schedules
  stage: build
  cache:
    untracked: true
    key: ${CI_COMMIT_REF_SLUG}
    paths:
    - dl
# don't keep workdir
  script:
    - ./build.sh ramips.mt7621 -j8
#  artifacts:
#    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
#    paths:
#    - workdir/*/bin/targets/ramips
#    - dl
  tags:
  - m2runner

build:ipq40xx.generic:
  except:
    - schedules
  stage: build
  cache:
    untracked: true
    key: ${CI_COMMIT_REF_SLUG}
    paths:
    - dl
    - workdir/*
  script:
    - ./build.sh ipq40xx.generic -j2
  tags:
  - m2runner

nightly_build:ipq40xx.generic:
  only:
    - schedules
  stage: build
  cache:
    untracked: true
    key: ${CI_COMMIT_REF_SLUG}
    paths:
    - dl
# don't keep workdir
  script:
    - ./build.sh ipq40xx.generic -j8
#  artifacts:
#    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
#    paths:
#    - workdir/*/bin/targets/ipq40xx.generic
#    - dl
  tags:
  - m2runner

