stages:
- init
- build
- test
- deploy

include:
  - local: '/gitlab-ci/m2runner-master.yml'
  - local: '/gitlab-ci/m2runner-nightly.yml'
  - local: '/gitlab-ci/docker.yml'
  - local: '/gitlab-ci/docker2.yml'

