# define globally used variables with defaults. these are
# overwritten by gitlab ci configuration of a project
#variables:
#  FF_UPLOAD_DIR: ""
#  FF_BUILD_TAG: ""
#  FF_GITLAB_REMOVE_WORKDIR: 0
#  FF_GITLAB_REMOVE_DL: 0


stages:
- init
- build
- test
- deploy

include:
  - local: '/gitlab-ci/m3runner-tags.yml'
  - local: '/gitlab-ci/m3runner-master.yml'
  - local: '/gitlab-ci/docker2-yaro.yml'
  - local: '/gitlab-ci/docker.yml'
