#!/bin/sh /etc/rc.common
# Copyright (C) freiunk-dresden

START=98
start() {

	# check if overlayfs exist. If not some router are updated in two steps.
	# first: initramfs-kernel (which does not create overlay, and must allow to
	#			   run second step from ssh)
	# second: sysupgrade image via ssh (which creates overlay).
	# ddmesh-init.d.sh requires working overlayfs (else endless boot)
	if [ -n "$(mount | grep overlayfs)" ]; then
		/usr/lib/ddmesh/ddmesh-init.d.sh start
	fi
}
