#!/bin/sh

#ddmesh_hotplug_ifname='eth0'
#ddmesh_hotplug_network='wifi2'
#ddmesh_hotplug_state=up | down | unknown
#ddmesh_hotplug_type='network'

case $ddmesh_hotplug_type in
	network)
		logger -t "ddmesh_hotplug:" "setting addtional firewall rules"

#		if [ "$ddmesh_hotplug_state" = "down" ]; then
#			eval $(/usr/lib/ddmesh/ddmesh-utils-network-info.sh $ddmesh_hotplug_network)
#		else
#		fi		
		
		;;
esac
