#!/bin/sh
# Copyright (C) 2006 - present, Stephan Enderlein<stephan@freifunk-dresden.de>
# GNU General Public License Version 3

test -f /tmp/freifunk-running || exit 0

TAG="ddmesh-hotplug-iface"
TAG2="20-firewall"

logger -t "$TAG" "$TAG2: net:[$INTERFACE] action:$ACTION type:$DEVTYPE devicename:[$DEVICENAME] devpath:$DEVPATH"
[ ifup = "$ACTION" -o ifdown = "$ACTION" ] && {
	[ "wan" = "$INTERFACE" -o "lan" = "$INTERFACE" -o "wifi2" = "$INTERFACE" ] && /usr/lib/ddmesh/ddmesh-firewall-addons.sh firewall-update
}
