#!/bin/sh
# Copyright (C) 2006 - present, Stephan Enderlein<stephan@freifunk-dresden.de>
# GNU General Public License Version 3

# bmxd is started before
# and hotplug interfaces are added before touching /tmp/freifunk-running
# -> do not check for freifunk-running, else event gets lost

# use /etc/hotplug.d/iface  instead  /etc/hotplug.d/net because
# "net" is triggered serveral times during boot, but final state
# is only triggerred once via "iface"

TAG="ddmesh-hotplug-iface"
TAG2="30-bmxd"

logger -t "$TAG" "$TAG2: net:[$INTERFACE] action:$ACTION type:$DEVTYPE devicename:[$DEVICENAME] devpath:$DEVPATH"
if [ "$INTERFACE" = "wifi_adhoc" -o "$INTERFACE" = "wifi_mesh2g" -o "$INTERFACE" = "wifi_mesh5g" ]; then

	# INTERFACE contains network name, have to determine interace name
	eval $(/usr/lib/ddmesh/ddmesh-utils-network-info.sh all)
	eval ifname=\$${INTERFACE}_ifname

	if [ "$ACTION" = "ifup" ]; then
		logger -t "$TAG" "$TAG2: add [$ifname] to bmxd"
		/usr/lib/ddmesh/ddmesh-bmxd.sh add_if_wifi $ifname
	fi
	if [ "$ACTION" = "ifdown" ]; then
		logger -t "$TAG" "$TAG2: remove [$ifname] from bmxd"
		/usr/lib/ddmesh/ddmesh-bmxd.sh del_if $ifname
	fi
fi
