#!/bin/sh

# bmxd is started before 
# and hotplug interfaces are added before touching /tmp/freifunk-running
# -> do not check for freifunk-running, else event gets lost

# use /etc/hotplug.d/iface  instead  /etc/hotplug.d/net because
# "net" is triggered serveral times during boot, but final state
# is only triggerred once via "iface"

logger -t ddmesh "network-hotplug 30-bmxd: network: [$INTERFACE] action:$ACTION type:$DEVTYPE devicename:[$DEVICENAME] devpath:$DEVPATH"
if [ "$INTERFACE" = "wifi_adhoc" -o "$INTERFACE" = "wifi2_mesh" -o "$INTERFACE" = "wifi5_mesh" ]; then

	# INTERFACE contains network name, have to determine interace name
	eval $(/usr/lib/ddmesh/ddmesh-utils-network-info.sh all)
	eval ifname=\$${INTERFACE}_ifname

	if [ "$ACTION" = "ifup" ]; then
		logger -t ddmesh "network-hotplug: add [$ifname] to bmxd"
		/usr/lib/ddmesh/ddmesh-bmxd.sh add_if $ifname
	fi
	if [ "$ACTION" = "ifdown" ]; then
		logger -t ddmesh "network-hotplug: remove [$ifname] from bmxd"
		/usr/lib/ddmesh/ddmesh-bmxd.sh del_if $ifname
	fi
fi
