#!/bin/sh

# bmxd is started before 
# and hotplug interfaces are added before touching /tmp/freifunk-running
# -> do not check for freifunk-running, else event gets lost

# use /etc/hotplug.d/iface  instead  /etc/hotplug.d/net because
# "net" is triggered serveral times during boot, but final state
# is only triggerred once via "iface"

logger -t ddmesh "network-hotplug 30-bmxd: [$INTERFACE] action:$ACTION type:$DEVTYPE devicename:[$DEVICENAME] devpath:$DEVPATH"
if [ "$INTERFACE" = "wifi_adhoc" -o "$INTERFACE" = "wifi_mesh" ]; then

	if [ "$ACTION" = "ifup" ]; then
		logger -t ddmesh "network-hotplug: add [$INTERFACE] to bmxd"
		/usr/lib/ddmesh/ddmesh-bmxd.sh add_if $INTERFACE
	fi
	if [ "$ACTION" = "ifdown" ]; then
		logger -t ddmesh "network-hotplug: remove [$INTERFACE] from bmxd"
		/usr/lib/ddmesh/ddmesh-bmxd.sh del_if $INTERFACE
	fi
fi
