#!/bin/sh

test -f /tmp/freifunk-running || exit 0

# update resolv.conf.final if wan cable is inserted after bmxd has started

if [ "$INTERFACE" = "wan" -o "$INTERFACE" = "wwan" ]; then
	if [ "$ACTION" = "ifup" ]; then
		logger -t ddmesh "network-hotplug iface: update resolv.conf.final"
		/usr/lib/bmxd/bmxd-gateway.sh init
	fi
fi
