#!/bin/sh
# Copyright (C) 2006 - present, Stephan Enderlein<stephan@freifunk-dresden.de>
# GNU General Public License Version 3

# update "status" led when wifi (adhoc) is down/up

test -f /tmp/freifunk-running || exit 0

[ ifdown = "$ACTION" ] && {
	[ wifi = "$INTERFACE" -o wifi2 = "$INTERFACE" ] && /usr/lib/ddmesh/ddmesh-led.sh wifi off
}

[ ifup = "$ACTION" ] && {
	[ wifi = "$INTERFACE" -o wifi2 = "$INTERFACE" ] && /usr/lib/ddmesh/ddmesh-led.sh wifi alive
}
