#!/bin/sh

# ddmesh-utils-network-info.sh uses cached data. update cache when interfaces
# become up (and have got IP)

logger -t ddmesh "network-hotplug 75-update-network-info: [$INTERFACE] action:$ACTION type:$DEVTYPE devicename:[$DEVICENAME] devpath:$DEVPATH"

[ ifup = "$ACTION" -o ifdown = "$ACTION" ] && {
	/usr/lib/ddmesh/ddmesh-utils-network-info.sh update
}
