#!/bin/sh
# Copyright (C) 2006 - present, Stephan Enderlein<stephan@freifunk-dresden.de>
# GNU General Public License Version 3

TAG="ddmesh-hotplug-usb"

logger -t ${TAG} "action:[$ACTION] type:[$DEVTYPE] dev:[$DEVICENAME] drv:[$DRIVER] devpath:[$DEVPATH]"

if [ -n "$DEVPATH" ]; then
	vid=$(cat /sys$DEVPATH/../idVendor)
	pid=$(cat /sys$DEVPATH/../idProduct)
	product=$(cat /sys$DEVPATH/../product)
	speed=$(cat /sys$DEVPATH/../speed)
	ifname="$(ls /sys${DEVPATH}/net/)"

	logger -t ${TAG} "    ifname=[${ifname}], vid=[$vid], pid=[$pid], product:[$product], usbspeed=[$speed]"
fi
