#!/bin/sh /etc/rc.common
# Copyright (C) 2020 Yaroslav Petrov <info@lank.me>
# This is free software, see license/license.txt for more information.

START=99
STOP=10

USE_PROCD=1
NAME=ddmesh-tasks
PROG=/usr/sbin/ddmesh-tasks.sh

start_service()
{
         procd_open_instance $NAME 
         procd_set_param command "$PROG"

         # respawn automatically after 1 minuteif something died, be careful if you have an alternative process supervisor
         # if process dies sooner than respawn_threshold, it is considered crashed and after 5 retries the service is stopped
         procd_set_param respawn ${respawn_threshold:-60} ${respawn_timeout:-5} ${respawn_retry:-5}

         procd_set_param limits nice="20"
         procd_set_param stdout 1
         procd_set_param stderr 1
         procd_set_param pidfile /var/run/$NAME.pid
         procd_close_instance
}

reload_service()
{
        echo "restarting service"
        stop
        start
}


