#!/bin/sh
# Copyright (C) 2010 Stephan Enderlein <stephan@freifunk-dresden.de>
# GNU General Public License Version 3

TAG="ddmesh-hotplug-net"
logger -t "$TAG" "event: iface:[$INTERFACE] action:$ACTION type:$DEVTYPE dev:[$DEVICENAME] devpath:$DEVPATH"
