####### docker ############

# re-create symlinks because gitlab removes it before starting each single job.
# /builds/dl is an empty directory created during docker image creation.
# This directory is used as mount point to pass in /mycache from host machine.
# I use this to avoid downloading/cloning from openwrt.org for each commit
# to gitlab.freifunk-dresden.de
# "before_script" can be global or local to a job. but
# but then it is same as if I put the command just before build command.
# when "before_script" is global, then all global before_scripts are
# executed independent of any job or runner (without any tags)


default:
  # image is on hub.docker.com. NOTE: always specify a tag and do not use latest!
  # this is because if a latest image is already on host, this is not updated automatically.
  # Using tags always ensures that the correct build environment is used
  image: freifunkdresden/openwrt-docker-build:v3

docker:init:
  except:
    - schedules
    - master
    - /^yaro-.*$/
    - /^T_FIRMWARE_.*$/
    - /^TESTING_FIRMWARE_.*$/
    - /^R_FIRMWARE_.*$/
  stage: init
  script:
    - echo "FF_GITLAB_REMOVE_DL = [${FF_GITLAB_REMOVE_DL}]"
    - echo "FF_GITLAB_REMOVE_WORKDIR = [${FF_GITLAB_REMOVE_WORKDIR}]"
    - echo "FF_UPLOAD_DIR = [${FF_UPLOAD_DIR}]"
    - mkdir -p /mycache/dl
    - ln -s /mycache/dl
    - mkdir -p /mycache/workdir
    - ln -s /mycache/workdir
    - test "${FF_GITLAB_REMOVE_DL}" = "1" && rm -rf ~/mycache/dl/*
    - test "${FF_GITLAB_REMOVE_WORKDIR}" = "1" && rm -rf ~/mycache/workdir/*
    - /bin/true
  tags:
    - docker

docker:ar71xx.tiny:
  except:
    - schedules
    - master
    - /^yaro-.*$/
    - /^T_FIRMWARE_.*$/
    - /^TESTING_FIRMWARE_.*$/
    - /^R_FIRMWARE_.*$/
  stage: build
  needs: ["docker:init"]
  script:
    - mkdir -p /mycache/dl
    - ln -s /mycache/dl
    - mkdir -p /mycache/workdir
    - ln -s /mycache/workdir
    - ./build.sh ar71xx.tiny.lowmem rerun -j"$(( $(nproc) + 1))"
  tags:
  - docker


docker:ar71xx.generic:
  except:
    - schedules
    - master
    - /^yaro-.*$/
    - /^T_FIRMWARE_.*$/
    - /^TESTING_FIRMWARE_.*$/
    - /^R_FIRMWARE_.*$/
  stage: build
  needs: ["docker:init"]
  script:
    - mkdir -p /mycache/dl
    - ln -s /mycache/dl
    - mkdir -p /mycache/workdir
    - ln -s /mycache/workdir
    - ./build.sh ar71xx.generic.* rerun -j"$(( $(nproc) + 1))"
  tags:
  - docker

docker:ar71xx.nand:
  except:
    - schedules
    - master
    - /^yaro-.*$/
    - /^T_FIRMWARE_.*$/
    - /^TESTING_FIRMWARE_.*$/
    - /^R_FIRMWARE_.*$/
  stage: build
  needs: ["docker:init"]
  script:
    - mkdir -p /mycache/dl
    - ln -s /mycache/dl
    - mkdir -p /mycache/workdir
    - ln -s /mycache/workdir
    - ./build.sh ar71xx.nand.* rerun -j"$(( $(nproc) + 1))"
  tags:
  - docker


docker:x86.generic:
  except:
    - schedules
    - master
    - /^yaro-.*$/
    - /^T_FIRMWARE_.*$/
    - /^TESTING_FIRMWARE_.*$/
    - /^R_FIRMWARE_.*$/
  stage: build
  needs: ["docker:init"]
  script:
    - mkdir -p /mycache/dl
    - ln -s /mycache/dl
    - mkdir -p /mycache/workdir
    - ln -s /mycache/workdir
    - ./build.sh x86.generic rerun -j"$(( $(nproc) + 1))"
  tags:
  - docker

docker:x64.generic:
  except:
    - schedules
    - master
    - /^yaro-.*$/
    - /^T_FIRMWARE_.*$/
    - /^TESTING_FIRMWARE_.*$/
    - /^R_FIRMWARE_.*$/
  stage: build
  needs: ["docker:init"]
  script:
    - mkdir -p /mycache/dl
    - ln -s /mycache/dl
    - mkdir -p /mycache/workdir
    - ln -s /mycache/workdir
    - ./build.sh x64.generic rerun -j"$(( $(nproc) + 1))"
  tags:
  - docker


docker:ramips:
  except:
    - schedules
    - master
    - /^yaro-.*$/
    - /^T_FIRMWARE_.*$/
    - /^TESTING_FIRMWARE_.*$/
    - /^R_FIRMWARE_.*$/
  stage: build
  needs: ["docker:init"]
  script:
    - mkdir -p /mycache/dl
    - ln -s /mycache/dl
    - mkdir -p /mycache/workdir
    - ln -s /mycache/workdir
    - ./build.sh ramips.* rerun -j"$(( $(nproc) + 1))"
  tags:
  - docker


docker:lantiq:
  except:
    - schedules
    - master
    - /^yaro-.*$/
    - /^T_FIRMWARE_.*$/
    - /^TESTING_FIRMWARE_.*$/
    - /^R_FIRMWARE_.*$/
  stage: build
  needs: ["docker:init"]
  script:
    - mkdir -p /mycache/dl
    - ln -s /mycache/dl
    - mkdir -p /mycache/workdir
    - ln -s /mycache/workdir
    - ./build.sh lantiq.* rerun -j"$(( $(nproc) + 1))"
  tags:
  - docker

docker:ath79:
  except:
    - schedules
    - master
    - /^yaro-.*$/
    - /^T_FIRMWARE_.*$/
    - /^TESTING_FIRMWARE_.*$/
    - /^R_FIRMWARE_.*$/
  stage: build
  needs: ["docker:init"]
  script:
    - mkdir -p /mycache/dl
    - ln -s /mycache/dl
    - mkdir -p /mycache/workdir
    - ln -s /mycache/workdir
    - ./build.sh ath79.* rerun -j"$(( $(nproc) + 1))"
  tags:
  - docker

docker:ipq40xx:
  except:
    - schedules
    - master
    - /^yaro-.*$/
    - /^T_FIRMWARE_.*$/
    - /^TESTING_FIRMWARE_.*$/
    - /^R_FIRMWARE_.*$/
  stage: build
  needs: ["docker:init"]
  script:
    - mkdir -p /mycache/dl
    - ln -s /mycache/dl
    - mkdir -p /mycache/workdir
    - ln -s /mycache/workdir
    - ./build.sh ipq40xx.* rerun -j"$(( $(nproc) + 1))"
  tags:
  - docker

docker:sunxi:
  except:
    - schedules
    - master
    - /^yaro-.*$/
    - /^T_FIRMWARE_.*$/
    - /^TESTING_FIRMWARE_.*$/
    - /^R_FIRMWARE_.*$/
  stage: build
  needs: ["docker:init"]
  script:
    - mkdir -p /mycache/dl
    - ln -s /mycache/dl
    - mkdir -p /mycache/workdir
    - ln -s /mycache/workdir
    - ./build.sh sunxi.* rerun -j"$(( $(nproc) + 1))"
  tags:
  - docker

docker:mpc85xx:
  except:
    - schedules
    - master
    - /^yaro-.*$/
    - /^T_FIRMWARE_.*$/
    - /^TESTING_FIRMWARE_.*$/
    - /^R_FIRMWARE_.*$/
  stage: build
  needs: ["docker:init"]
  script:
    - mkdir -p /mycache/dl
    - ln -s /mycache/dl
    - mkdir -p /mycache/workdir
    - ln -s /mycache/workdir
    - ./build.sh mpc85xx.* rerun -j"$(( $(nproc) + 1))"
  tags:
  - docker

docker:bcm53xx.generic.arm:
  except:
    - schedules
    - master
    - /^yaro-.*$/
    - /^T_FIRMWARE_.*$/
    - /^TESTING_FIRMWARE_.*$/
    - /^R_FIRMWARE_.*$/
  stage: build
  needs: ["docker:init"]
  script:
    - mkdir -p /mycache/dl
    - ln -s /mycache/dl
    - mkdir -p /mycache/workdir
    - ln -s /mycache/workdir
    - ./build.sh bcm53xx.generic.arm rerun -j"$(( $(nproc) + 1))"
  tags:
  - docker

docker:21.ath79:
  except:
    - schedules
    - master
    - /^yaro-.*$/
    - /^T_FIRMWARE_.*$/
    - /^TESTING_FIRMWARE_.*$/
    - /^R_FIRMWARE_.*$/
  stage: build
  needs: ["docker:init"]
  script:
    - mkdir -p /mycache/dl
    - ln -s /mycache/dl
    - mkdir -p /mycache/workdir
    - ln -s /mycache/workdir
    - ./build.sh 21.ath79.* rerun -j"$(( $(nproc) + 1))"
  tags:
  - docker

# just to check also generation of final_output directory.
# e.g.: check missing firmware infos
docker:gen-upload-test:
  except:
    - schedules
    - master
    - /^yaro-.*$/
    - /^T_FIRMWARE_.*$/
    - /^TESTING_FIRMWARE_.*$/
    - /^R_FIRMWARE_.*$/
  stage: deploy
  needs: ["docker:ar71xx.tiny","docker:ar71xx.generic","docker:ar71xx.nand","docker:x86.generic","docker:x64.generic","docker:ramips","docker:lantiq","docker:ath79","docker:ipq40xx","docker:sunxi","docker:mpc85xx","docker:bcm53xx.generic.arm"]
  script:
    - mkdir -p /mycache/dl
    - ln -s /mycache/dl
    - mkdir -p /mycache/workdir
    - ln -s /mycache/workdir
    - ./gen-upload.sh all
    - ./build.sh list
  tags:
  - docker
