######## m2runner ################

# dl and workdir symlinks are removed by gitlab for each job
# so I need to recreate this
#  - ln -s ~/mycache/dl
#  - ln -s ~/mycache/workdir

nightly:init:
  only:
    - schedules
  stage: init       # special state, run before all other stages
  script:
    - ln -s ~/mycache/dl
    - ln -s ~/mycache/workdir
  # ensure that we have no old data. This is important when
  # generating download.json. Else all old openwrt images would be
  # included and mixed

  # dont delete dl, it is not so important to have different old version for
  # one packges, but it will reduce download overhead from external servers
  # every night. so just only delete workdirs to always have a clean build
    - test "$FF_GITLAB_REMOVE_DL" = "1" && rm -rf ~/mycache/dl/*
    - test "$FF_GITLAB_REMOVE_WORKDIR" = "1" && rm -rf ~/mycache/workdir/*
    - /bin/true
  tags:
  - m2runner

nightly:ar71xx.tiny:
  only:
    - schedules
  stage: build
  script:
    - ln -s ~/mycache/dl
    - ln -s ~/mycache/workdir
    - ./build.sh ar71xx.tiny.lowmem rerun -j8
  tags:
  - m2runner

nightly:ar71xx.generic:
  only:
    - schedules
  stage: build
  script:
    - ln -s ~/mycache/dl
    - ln -s ~/mycache/workdir
    - ./build.sh ar71xx.generic.* rerun -j8
  tags:
  - m2runner

nightly:x86.generic:
  only:
    - schedules
  stage: build
  script:
    - ln -s ~/mycache/dl
    - ln -s ~/mycache/workdir
    - ./build.sh x86.generic rerun -j8
  tags:
  - m2runner

nightly:x64.generic:
  only:
    - schedules
  stage: build
  script:
    - ln -s ~/mycache/dl
    - ln -s ~/mycache/workdir
    - ./build.sh x64.generic rerun -j8
  tags:
  - m2runner

nightly:ramips:
  only:
    - schedules
  stage: build
  script:
    - ln -s ~/mycache/dl
    - ln -s ~/mycache/workdir
    - ./build.sh ramips.* rerun -j8
  tags:
  - m2runner

nightly:ipq40xx:
  only:
    - schedules
  stage: build
  script:
    - ln -s ~/mycache/dl
    - ln -s ~/mycache/workdir
    - ./build.sh ipq40xx.generic.* rerun -j8
  tags:
  - m2runner

nightly:lantiq:
  only:
    - schedules
  stage: build
  script:
    - ln -s ~/mycache/dl
    - ln -s ~/mycache/workdir
    - ./build.sh lantiq.* rerun -j8
  tags:
  - m2runner

nightly:ath79:
  only:
    - schedules
  stage: build
  script:
    - ln -s ~/mycache/dl
    - ln -s ~/mycache/workdir
    - ./build.sh ath79.* rerun -j8
  tags:
  - m2runner

nightly:sunxi:
  only:
    - schedules
  stage: build
  script:
    - ln -s ~/mycache/dl
    - ln -s ~/mycache/workdir
    - ./build.sh sunxi.* rerun -j8
  tags:
  - m2runner

nightly:test:
  only:
    - schedules
  stage: test
  script:
    - echo "dummy"
  tags:
  - m2runner

nightly:deploy-upload:
  only:
    - schedules
  stage: deploy
  script:
    - ln -s ~/mycache/dl
    - ln -s ~/mycache/workdir
    - ./gen-upload.sh all
    # runner must have ssh key that are added to download server. on download server there is a user "stephan" who owns the download directories
    # add the runners public key to user stephan authorized_keys file
    - rsync -avz --info=all1 --delete -EH --progress final_output/*/* stephan@download.lxc:/var/www/files/$FF_UPLOAD_DIR/
    - rm -rf final_output
# artifacts are not needed (waste of disk storage), because they are uploaded to download server
#  artifacts:
#    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
#    expire_in: 2 days
#    paths:
#    - dl
#    - final_output
  tags:
  - m2runner

