######## m2runner ################

# dl and workdir symlinks are removed by gitlab for each job
# so I need to recreate this
before_script:
  - ln -s ~/mycache/dl
  - ln -s ~/mycache/workdir

ar71xx.tiny:
  except:
    - schedules
  stage: build
  script:
    - ./build.sh ar71xx.tiny.lowmem rerun -j2
  tags:
  - m2runner

ar71xx.generic:
  except:
    - schedules
  stage: build
  script:
    - ./build.sh ar71xx.generic.* rerun -j2
  tags:
  - m2runner

x86.generic:
  except:
    - schedules
  stage: build
  script:
    - ./build.sh x86.generic.* rerun -j2
  tags:
  - m2runner

x64.generic:
  except:
    - schedules
  stage: build
  script:
    - ./build.sh x64.generic.* rerun -j2
  tags:
  - m2runner

ramips:
  except:
    - schedules
  stage: build
  script:
    - ./build.sh ramips.* rerun -j2
  tags:
  - m2runner

ipq40xx:
  except:
    - schedules
  stage: build
  script:
    - ./build.sh ipq40xx.* rerun -j2
  tags:
  - m2runner

lantiq:
  except:
    - schedules
  stage: build
  script:
    - ./build.sh lantiq.* rerun -j2
  tags:
  - m2runner


