######## m2runner ################
# there are two jobs, one for each commit and one for nightly scheduled job
# nightly is the one that keeps artifacts (result of built) and which
# then deployed later (see option "only").
# deploy stage should be added.

nightly:ar71xx.tiny:
  only:
    - schedules
  stage: build
  cache:
    untracked: true
    key: ${CI_COMMIT_REF_SLUG}-nightly
    paths:
    - dl
# don't keep workdir
  script:
    - ./build.sh ar71xx.tiny -j8
#  artifacts:
#    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
#    paths:
#    - workdir/*/bin/targets/ar71xx/tiny
#    - dl
  tags:
  - m2runner

nightly:ar71xx.generic:
  only:
    - schedules
  stage: build
  cache:
    untracked: true
    key: ${CI_COMMIT_REF_SLUG}-nightly
    paths:
    - dl
# don't keep workdir
  script:
    - ./build.sh ar71xx.generic -j8
#  artifacts:
#    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
#    paths:
#    - workdir/*/bin/targets/ar71xx/generic
#    - dl
  tags:
  - m2runner

nightly:x86.generic:
  only:
    - schedules
  stage: build
  cache:
    untracked: true
    key: ${CI_COMMIT_REF_SLUG}-nightly
    paths:
    - dl
# don't keep workdir
  script:
    - ./build.sh x86.generic -j8
#  artifacts:
#    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
#    paths:
#    - workdir/*/bin/targets/x86/generic
#    - dl
  tags:
  - m2runner

nightly:ramips.mt7621:
  only:
    - schedules
  stage: build
  cache:
    untracked: true
    key: ${CI_COMMIT_REF_SLUG}-nightly
    paths:
    - dl
# don't keep workdir
  script:
    - ./build.sh ramips.mt7621 -j8
#  artifacts:
#    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
#    paths:
#    - workdir/*/bin/targets/ramips
#    - dl
  tags:
  - m2runner

nightly:ipq40xx.generic:
  only:
    - schedules
  stage: build
  cache:
    untracked: true
    key: ${CI_COMMIT_REF_SLUG}-nightly
    paths:
    - dl
# don't keep workdir
  script:
    - ./build.sh ipq40xx.generic -j8
#  artifacts:
#    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
#    paths:
#    - workdir/*/bin/targets/ipq40xx.generic
#    - dl
  tags:
  - m2runner

