######## m2runner ################
# there are two jobs, one for each commit and one for nightly scheduled job
# nightly is the one that keeps artifacts (result of built) and which
# then deployed later (see option "only").
# deploy stage should be added.

nightly:ar71xx.tiny:
  only:
    - schedules
  stage: build
  cache:
    untracked: true
    key: ${CI_COMMIT_REF_SLUG}-nightly
    paths:
    - dl
# don't keep workdir
  script:
    - ./build.sh ar71xx.tiny -j8
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
    paths:
     - workdir/*/bin/targets/ar71xx/tiny
#     - dl
  tags:
  - m2runner

nightly:ar71xx.generic:
  only:
    - schedules
  stage: build
  cache:
    untracked: true
    key: ${CI_COMMIT_REF_SLUG}-nightly
    paths:
    - dl
# don't keep workdir
  script:
    - ./build.sh ar71xx.generic -j8
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
    paths:
    - workdir/*/bin/targets/ar71xx/generic
#    - dl
  tags:
  - m2runner

nightly:x86.generic:
  only:
    - schedules
  stage: build
  cache:
    untracked: true
    key: ${CI_COMMIT_REF_SLUG}-nightly
    paths:
    - dl
# don't keep workdir
  script:
    - ./build.sh x86.generic -j8
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
    paths:
    - workdir/*/bin/targets/x86/generic
#    - dl
  tags:
  - m2runner

nightly:ramips.mt7621:
  only:
    - schedules
  stage: build
  cache:
    untracked: true
    key: ${CI_COMMIT_REF_SLUG}-nightly
    paths:
    - dl
# don't keep workdir
  script:
    - ./build.sh ramips.mt7621 -j8
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
    paths:
    - workdir/*/bin/targets/ramips
#    - dl
  tags:
  - m2runner

nightly:ipq40xx.generic:
  only:
    - schedules
  stage: build
  cache:
    untracked: true
    key: ${CI_COMMIT_REF_SLUG}-nightly
    paths:
    - dl
# don't keep workdir
  script:
    - ./build.sh ipq40xx.generic -j8
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
    paths:
    - workdir/*/bin/targets/ipq40xx/generic
#    - dl
  tags:
  - m2runner

nightly:lantiq.xrx200:
  only:
    - schedules
  stage: build
  cache:
    untracked: true
    key: ${CI_COMMIT_REF_SLUG}-nightly
    paths:
    - dl
# don't keep workdir
  script:
    - ./build.sh lantiq.xrx200 -j8
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
    paths:
    - workdir/*/bin/targets/lantiq/xrx200
#    - dl
  tags:
  - m2runner



# this build job will wait for all other jobs to ensure
# that all downloaded packages are stored. 
# beause jobs are run parallel (no specific order) I have
# to use a separae stage. 
# all artifacts are passed to higher stage.
# because I use the same cache, I can simply pass the "dl" as
# artifact to next stage.
nightly:dl:
  only:
    - schedules
  stage: dl_stage
  cache:
    untracked: true
    key: ${CI_COMMIT_REF_SLUG}-nightly
    paths:
    - dl
  script: 
    - 'true'
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
    paths:
    - dl
    - workdir/*/bin/targets
  tags:
  - m2runner

nightly:deploy:
  only:
    - schedules
  stage: deploy
  script: 
    - ./gen-upload.sh all
    # runner must have ssh key that are added to download server. on download server there is a user "stephan" who owns the download directories
    # add the runners public key to user stephan authorized_keys file
    - rsync -avz --info=all1 --delete -EH --progress final_output/* stephan@download.lxc:/var/www/files/nightlybuilt/
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
    paths:
    - dl
    - final_output
  tags:
  - m2runner


