######## m2runner ################

before_script:
  - ln -s ~/mycache/dl
  - ln -s ~/mycache/workdir
  # ensure that we have no old data. This is important when
  # generating download.json. Else all old openwrt images would be
  # included and mixed
  - rm -rf ~/mycache/dl/*
  - rm -rf ~/mycache/workdir/*

nightly:ar71xx.tiny:
  only:
    - schedules
  stage: build
  script:
    - ./build.sh ar71xx.tiny rerun -j8
  tags:
  - m2runner

nightly:ar71xx.generic:
  only:
    - schedules
  stage: build
  script:
    - ./build.sh ar71xx.generic rerun -j8
  tags:
  - m2runner

nightly:x86.generic:
  only:
    - schedules
  stage: build
  script:
    - ./build.sh x86.generic rerun -j8
  tags:
  - m2runner

nightly:ramips.mt7621:
  only:
    - schedules
  stage: build
  script:
    - ./build.sh ramips.mt7621 rerun -j8
  tags:
  - m2runner

nightly:ipq40xx.generic:
  only:
    - schedules
  stage: build
  script:
    - ./build.sh ipq40xx.generic rerun -j8
  tags:
  - m2runner

nightly:lantiq.xrx200:
  only:
    - schedules
  stage: build
  script:
    - ./build.sh lantiq.xrx200 rerun -j8
  tags:
  - m2runner

nightly:ath79.nand:
  only:
    - schedules
  stage: build
  script:
    - ./build.sh ath79.nand rerun -j8
  tags:
  - m2runner

nightly:deploy:
  only:
    - schedules
  stage: deploy
  script: 
    - ./gen-upload.sh all
    # runner must have ssh key that are added to download server. on download server there is a user "stephan" who owns the download directories
    # add the runners public key to user stephan authorized_keys file
    - rsync -avz --info=all1 --delete -EH --progress final_output/*/* stephan@download.lxc:/var/www/files/nightly/
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
    expire_in: 2 days
    paths:
    - dl
    - final_output
  tags:
  - m2runner


