######## m3runner ################

# dl and workdir symlinks are removed by gitlab for each job
# so I need to recreate this
#  - ln -s ~/mycache/dl
#  - ln -s ~/mycache/workdir

m3tags:init:
  only:
    - /^R_FIRMWARE_/
    - /^TESTING_FIRMWARE_/
    - /^T_FIRMWARE_/
  stage: init       # special state, run before all other stages
  script:
    - ln -s ~/mycache/dl
    - ln -s ~/mycache/workdir
  # ensure that we have no old data. This is important when
  # generating download.json. Else all old openwrt images would be
  # included and mixed

    - echo "FF_GITLAB_REMOVE_DL = [${FF_GITLAB_REMOVE_DL}]"
    - echo "FF_GITLAB_REMOVE_WORKDIR = [${FF_GITLAB_REMOVE_WORKDIR}]"
    - echo "FF_UPLOAD_DIR = [${FF_UPLOAD_DIR}]"

  # dont delete dl, it is not so important to have different old version for
  # one packges, but it will reduce download overhead from external servers
  # every night. so just only delete workdirs to always have a clean build
    - test "${FF_GITLAB_REMOVE_DL}" = "1" && rm -rf ~/mycache/dl/*
    - test "${FF_GITLAB_REMOVE_WORKDIR}" = "1" && rm -rf ~/mycache/workdir/*
    - /bin/true
  tags:
    - m3runner

m3tags:ar71xx.tiny.lowmem:
  only:
    - /^R_FIRMWARE_/
    - /^TESTING_FIRMWARE_/
    - /^T_FIRMWARE_/
  stage: build
  needs: ["m3tags:init"]
  script:
    - ln -s ~/mycache/dl
    - ln -s ~/mycache/workdir
    - ./build.sh ar71xx.tiny.lowmem rerun -j"$(( $(nproc) + 1))"
  tags:
    - m3runner

m3tags:ar71xx.generic.lowmem:
  only:
    - /^R_FIRMWARE_/
    - /^TESTING_FIRMWARE_/
    - /^T_FIRMWARE_/
  stage: build
  needs: ["m3tags:init"]
  script:
    - ln -s ~/mycache/dl
    - ln -s ~/mycache/workdir
    - ./build.sh ar71xx.generic.lowmem rerun -j"$(( $(nproc) + 1))"
  tags:
    - m3runner

m3tags:x86.64.offloader:
  only:
    - /^R_FIRMWARE_/
    - /^TESTING_FIRMWARE_/
    - /^T_FIRMWARE_/
  stage: build
  needs: ["m3tags:init"]
  script:
    - ln -s ~/mycache/dl
    - ln -s ~/mycache/workdir
    - ./build.sh x86.64.offloader rerun -j"$(( $(nproc) + 1))"
  tags:
    - m3runner

m3tags:ramips:
  only:
    - /^R_FIRMWARE_/
    - /^TESTING_FIRMWARE_/
    - /^T_FIRMWARE_/
  stage: build
  needs: ["m3tags:init"]
  script:
    - ln -s ~/mycache/dl
    - ln -s ~/mycache/workdir
    - ./build.sh ramips.* rerun -j"$(( $(nproc) + 1))"
  tags:
    - m3runner

m3tags:ipq40xx:
  only:
    - /^R_FIRMWARE_/
    - /^TESTING_FIRMWARE_/
    - /^T_FIRMWARE_/
  stage: build
  needs: ["m3tags:init"]
  script:
    - ln -s ~/mycache/dl
    - ln -s ~/mycache/workdir
    - ./build.sh ipq40xx.generic.* rerun -j"$(( $(nproc) + 1))"
  tags:
    - m3runner

m3tags:lantiq:
  only:
    - /^R_FIRMWARE_/
    - /^TESTING_FIRMWARE_/
    - /^T_FIRMWARE_/
  stage: build
  needs: ["m3tags:init"]
  script:
    - ln -s ~/mycache/dl
    - ln -s ~/mycache/workdir
    - ./build.sh lantiq.* rerun -j"$(( $(nproc) + 1))"
  tags:
    - m3runner

m3tags:ath79:
  only:
    - /^R_FIRMWARE_/
    - /^TESTING_FIRMWARE_/
    - /^T_FIRMWARE_/
  stage: build
  needs: ["m3tags:init"]
  script:
    - ln -s ~/mycache/dl
    - ln -s ~/mycache/workdir
    - ./build.sh ath79.* rerun -j"$(( $(nproc) + 1))"
  tags:
    - m3runner

m3tags:sunxi:
  only:
    - /^R_FIRMWARE_/
    - /^TESTING_FIRMWARE_/
    - /^T_FIRMWARE_/
  stage: build
  needs: ["m3tags:init"]
  script:
    - ln -s ~/mycache/dl
    - ln -s ~/mycache/workdir
    - ./build.sh sunxi.* rerun -j"$(( $(nproc) + 1))"
  tags:
    - m3runner

m3tags:mpc85xx:
  only:
    - /^R_FIRMWARE_/
    - /^TESTING_FIRMWARE_/
    - /^T_FIRMWARE_/
  stage: build
  needs: ["m3tags:init"]
  script:
    - ln -s ~/mycache/dl
    - ln -s ~/mycache/workdir
    - ./build.sh mpc85xx.* rerun -j"$(( $(nproc) + 1))"
  tags:
    - m3runner

m3tags:test:
  only:
    - /^R_FIRMWARE_/
    - /^TESTING_FIRMWARE_/
    - /^T_FIRMWARE_/
  stage: test
  needs: ["m3tags:ar71xx.tiny.lowmem","m3tags:ar71xx.generic.lowmem","m3tags:x86.64.offloader","m3tags:ramips","m3tags:lantiq","m3tags:ath79","m3tags:ipq40xx","m3tags:sunxi","m3tags:mpc85xx"]
  script:
    - ln -s ~/mycache/dl
    - ln -s ~/mycache/workdir
    - ./build.sh list
  tags:
    - m3runner

m3tags:upload:
  only:
    # DO NOT UPLOAD for branch: R_FIRMWARE....
    - /^TESTING_FIRMWARE_/
    - /^T_FIRMWARE_/
  stage: deploy
  needs: ["m3tags:test"]
  when: manual
  script:
    - |
      if [ -z "${FF_UPLOAD_DIR}" -o "${FF_UPLOAD_DIR}" = "nightly" ]; then
        echo "FF_UPLOAD_DIR not defined! Aborting."
        exit 1
      fi
    - echo "FF_UPLOAD_DIR = [${FF_UPLOAD_DIR}]"
    - ln -s ~/mycache/dl
    - ln -s ~/mycache/workdir
    - ./gen-upload.sh all
    - |
      # gitlab-runner's public ssh key must added to /home/deploy-firmware/.ssh/authorized_keys.
      # On download server there is a user "deploy-firmware" who owns the download directories.
      if [ -n "${FF_UPLOAD_DIR}" ]; then
        rsync -avz --info=all1 --delete -EH --progress final_output/*/* deploy-firmware@download.intern:/var/www/files/firmware/${FF_UPLOAD_DIR}/
      fi
      rm -rf final_output
# artifacts are not needed (waste of disk storage), because they are uploaded to download server
  tags:
    - m3runner
