######## m3runner ################

# dl and workdir symlinks are removed by gitlab for each job
# so I need to recreate this
#  - ln -s ~/mycache/dl
#  - ln -s ~/mycache/workdir

m3:init:
  only:
    - master
  stage: init       # special state, run before all other stages
  script:
    - ln -s ~/mycache/dl
    - ln -s ~/mycache/workdir
  # ensure that we have no old data. This is important when
  # generating download.json. Else all old openwrt images would be
  # included and mixed

    - echo "FF_GITLAB_REMOVE_DL = [${FF_GITLAB_REMOVE_DL}]"
    - echo "FF_GITLAB_REMOVE_WORKDIR = [${FF_GITLAB_REMOVE_WORKDIR}]"
    - echo "FF_UPLOAD_DIR = [${FF_UPLOAD_DIR}]"

  # dont delete dl, it is not so important to have different old version for
  # one packges, but it will reduce download overhead from external servers
  # every night. so just only delete workdirs to always have a clean build
    - test "${FF_GITLAB_REMOVE_DL}" = "1" && rm -rf ~/mycache/dl/*
    - test "${FF_GITLAB_REMOVE_WORKDIR}" = "1" && rm -rf ~/mycache/workdir/*
    - /bin/true
  tags:
  - m3runner

m3:ar71xx.tiny.lowmem:
  only:
    - master
  stage: build
  needs: ["m3:init"]
  script:
    - ln -s ~/mycache/dl
    - ln -s ~/mycache/workdir
    - ./build.sh ar71xx.tiny.lowmem rerun -j"$(( $(nproc) + 1))"
  tags:
  - m3runner

m3:ar71xx.generic.lowmem:
  only:
    - master
  stage: build
  needs: ["m3:init"]
  script:
    - ln -s ~/mycache/dl
    - ln -s ~/mycache/workdir
    - ./build.sh ar71xx.generic.lowmem rerun -j"$(( $(nproc) + 1))"
  tags:
  - m3runner

m3:x86.generic.offloader:
  only:
    - master
  stage: build
  needs: ["m3:init"]
  script:
    - ln -s ~/mycache/dl
    - ln -s ~/mycache/workdir
    - ./build.sh x86.generic.offloader rerun -j"$(( $(nproc) + 1))"
  tags:
  - m3runner

m3:x86.64.offloader:
  only:
    - master
  stage: build
  needs: ["m3:init"]
  script:
    - ln -s ~/mycache/dl
    - ln -s ~/mycache/workdir
    - ./build.sh x86.64.offloader rerun -j"$(( $(nproc) + 1))"
  tags:
  - m3runner

m3:ramips:
  only:
    - master
  stage: build
  needs: ["m3:init"]
  script:
    - ln -s ~/mycache/dl
    - ln -s ~/mycache/workdir
    - ./build.sh ramips.* rerun -j"$(( $(nproc) + 1))"
  tags:
  - m3runner

m3:ipq40xx:
  only:
    - master
  stage: build
  needs: ["m3:init"]
  script:
    - ln -s ~/mycache/dl
    - ln -s ~/mycache/workdir
    - ./build.sh ipq40xx.generic.* rerun -j"$(( $(nproc) + 1))"
  tags:
  - m3runner

m3:lantiq:
  only:
    - master
  stage: build
  needs: ["m3:init"]
  script:
    - ln -s ~/mycache/dl
    - ln -s ~/mycache/workdir
    - ./build.sh lantiq.* rerun -j"$(( $(nproc) + 1))"
  tags:
  - m3runner

m3:ath79:
  only:
    - master
  stage: build
  needs: ["m3:init"]
  script:
    - ln -s ~/mycache/dl
    - ln -s ~/mycache/workdir
    - ./build.sh ath79.* rerun -j"$(( $(nproc) + 1))"
  tags:
  - m3runner

m3:sunxi:
  only:
    - master
  stage: build
  needs: ["m3:init"]
  script:
    - ln -s ~/mycache/dl
    - ln -s ~/mycache/workdir
    - ./build.sh sunxi.* rerun -j"$(( $(nproc) + 1))"
  tags:
  - m3runner

m3:mpc85xx:
  only:
    - master
  stage: build
  needs: ["m3:init"]
  script:
    - ln -s ~/mycache/dl
    - ln -s ~/mycache/workdir
    - ./build.sh mpc85xx.* rerun -j"$(( $(nproc) + 1))"
  tags:
  - m3runner


m3:bcm53xx.generic.arm:
  only:
    - master
  stage: build
  needs: ["m3:init"]
  script:
    - ln -s ~/mycache/dl
    - ln -s ~/mycache/workdir
    - ./build.sh bcm53xx.generic.arm rerun -j"$(( $(nproc) + 1))"
  tags:
  - m3runner

m3:21.ath79:
  only:
    - master
  stage: build
  needs: ["m3:init"]
  script:
    - ln -s ~/mycache/dl
    - ln -s ~/mycache/workdir
    - ./build.sh 21.ath79.* rerun -j"$(( $(nproc) + 1))"
  tags:
  - m3runner


m3:test:
  only:
    - master
  stage: test
  needs: ["m3:ar71xx.tiny.lowmem","m3:ar71xx.generic.lowmem","m3:x86.generic.offloader","m3:x86.64.offloader","m3:ramips","m3:lantiq","m3:ath79","m3:ipq40xx","m3:sunxi","m3:mpc85xx", "m3:bcm53xx.generic.arm"]
  script:
    - ln -s ~/mycache/dl
    - ln -s ~/mycache/workdir
    - ./build.sh list
  tags:
  - m3runner

m3:upload:
  only:
    - master
  stage: deploy
  needs: ["m3:ar71xx.tiny.lowmem","m3:ar71xx.generic.lowmem","m3:x86.generic.offloader","m3:x86.64.offloader","m3:ramips","m3:lantiq","m3:ath79","m3:ipq40xx","m3:sunxi","m3:mpc85xx", "m3:bcm53xx.generic.arm"]
  script:
    - ln -s ~/mycache/dl
    - ln -s ~/mycache/workdir
    - ./gen-upload.sh all
    # gitlab-runner's public ssh key must added to /home/deploy-firmware/.ssh/authorized_keys.
    # On download server there is a user "deploy-firmware" who owns the download directories.
    - echo "FF_UPLOAD_DIR = [${FF_UPLOAD_DIR}]"
    - ([ -n "${FF_UPLOAD_DIR}" ] && rsync -avz --info=all1 --delete -EH --progress final_output/*/* deploy-firmware@download.intern:/var/www/files/firmware/${FF_UPLOAD_DIR}/)
    - rm -rf final_output
# artifacts are not needed (waste of disk storage), because they are uploaded to download server
#  artifacts:
#    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
#    expire_in: 2 days
#    paths:
#    - dl
#    - final_output
  tags:
  - m3runner
