#!/bin/sh

CONF=/etc/openvpn/openvpn.conf

#modifies config to match firmware requirements

test -z "$1" && {
 echo "usage: gen-config.sh config-file"
 exit 1
}

echo "#generated by gen-config.sh" > $CONF

cat "$1" | sed '
s#^[	 ]*##
s/#.*$//
s#[ 	]*$##
/^$/d
/^#/d
/^dev/d
/^persist-key/d
/^persist-tun/d
/^keepalive/d
/^verb/d
/^script/d
/^up/d
/^down/d
/^route/d
/^ifconfig/d
/^resolv/d
/^float/d
/^dhcp-renew/d
/^dhcp-release/d
/^explicit-exit-notify/d
/^ping/d
/^pull-filter/d
s#^auth-user-pass.*#auth-user-pass openvpn.login#
' >> $CONF

#add newline
cat<<EOM >> $CONF

dev vpn0
dev-type tun
resolv-retry infinite
keepalive 10 30
script-security 2
float
route-noexec
ifconfig-noexec
up /etc/openvpn/up.sh 
down /etc/openvpn/down.sh
verb 3
EOM


